@url = http://localhost:5027

GET {{url}}/api/v1/weather
Accept: application/json

###

GET {{url}}/api/v1/users
Accept: application/json

###

GET {{url}}/api/v1/users/2
Accept: application/json

###
